### ISSUE TITLE
New google sites - header images not being detected

### ISSUE THREAD

**Issue by ayunami2000** [foooomio/view-background-image#14] opened 2018-10-10 11:24 UTC
honestly the title says it all.
take for example https://sites.google.com/ncsu.edu/thestateofwaterproject/the-politics-of-water-intro
try to rclick the big header w/ the image at the top
itll fail but i inspected it and it shouldnt

**Comment by foooomio** [comment] 2018-10-10 13:01
Thank you for the report.

The cause is that the `document.elementsFromPoint` API doesn't return the elemenet which has the background image. The API behaves in the same way on Firefox, too.

I'm not sure if the behavior is correct. I'll do some more research.

**Comment by foooomio** [comment] 2018-10-19 18:02
I finally noticed that one of the classes of the element has the `pointer-events: none;` property. `document.elementsFromPoint` doesn't return those elements. (cf. https://drafts.csswg.org/cssom-view/#dom-document-elementfrompoint )

I'm thinking about a solution.

**Comment by ayunami2000** [comment] 2018-10-20 05:08
Maybe go through all elements and remove pointer events from them and store those elements, then try to detect the background and then add back the pointer events?

**Comment by foooomio** [comment] 2018-10-20 10:16
Thanks for your advice, but I decided to implement hit-testing for all of the elements on the document instead of using `document.elementsFromPoint`. See 84b0ac1832e4ae91b9ede9d8cef7aeca474e7a66.

The fix has been released in v2.7.1. Please check it out. Thank you.

**Closed by foooomio** 2018-10-20 10:16 UTC
Labels: bug
