### ISSUE TITLE
Problem with beta.nli.org.il

### ISSUE THREAD

**Issue by shraga100** [foooomio/view-background-image#18] opened 2019-07-28 17:30 UTC
## Page URL

https://beta.nli.org.il/he/books/NNL_ALEPH002021374/NLI

## Image URL

https://rosetta.nli.org.il/delivery/DeliveryManagerServlet?dps_func=stream&dps_pid=FL46834531

### OS

Windows

### Chrome Version

75.0.3770.142

### Extension Version

2.9.0

**Comment by foooomio** [comment] 2019-07-29 06:59
Hi, thank you for the report.

It seems a bug. Please give me some time to investigate.

**Comment by yossizahn** [comment] 2019-07-29 13:58
Hi,
I did some debugging, and it seems that the problem is that the `"contextmenu"` event listener that sets the `x` and `y` coordinates belongs to the subframe that was clicked, however the `message` event listener that gets called belongs to the top frame, therefore it's `x` and `y` are still set to 0.

**Comment by shraga100** [comment] 2019-07-29 14:27
I encountered a similar problem on this site as well
  https://issuu.com/newsheet/docs/951
I do not know if this is the same problem ...

**Comment by foooomio** [comment] 2019-07-29 15:09
@yossizahn Thanks. I came to the same conclusion.

Somehow `chrome.contextMenus.onClicked` incorrectly passes the main frameId, not subframe frameId. This might be due to a Chrome's bug.

@shraga100 It is not the same problem.

It is because the image is drawn on the canvas element. It is impossible to get images from canvas elements.

**Comment by foooomio** [comment] 2019-07-29 16:28
Strangely, `frameUrl` returns the subframe url, but `frameId` returns the main frame ID. 😩 

![](https://user-images.githubusercontent.com/1075914/62064715-6c9bbf00-b268-11e9-833f-de119efd251c.png)

**Comment by foooomio** [comment] 2019-08-01 10:58
I found out that the cause is the CSS property `-webkit-user-drag` in `.BRnoselect`. When it is set to `none`, `chrome.contextMenus.onClicked` passes the main frameId to its listeners.

I'm not sure if this behavior is as specified.

**Comment by yossizahn** [comment] 2019-08-01 11:33
@foooomio, how did you arrive at this conclusion?
Disabling `-webkit-user-drag: none` in the devtools doesn't seem to solve the issue.

**Comment by foooomio** [comment] 2019-08-01 12:42
@yossizahn Oh sorry, you are right. I misunderstood. `-webkit-user-drag: none` doesn't matter. Once a page is turned, we can get the image.

**Comment by foooomio** [comment] 2022-10-25 18:05
Closing as it is not currently reproducible.

**Closed by foooomio** 2022-10-25 18:05 UTC
Labels: bug
