### ISSUE TITLE
Not working on Firefox 106?

### ISSUE THREAD

**Issue by rfischmann** [foooomio/view-background-image#32] opened 2022-10-21 09:42 UTC
After updating to Firefox 106, it seems the extension has stopped working. I don't see it in the contextual menu when right clicking anymore.

Anyone else?

**Comment by foooomio** [comment] 2022-10-21 09:52
Thank you for your report.

Firefox 106 has migrated from Manifest V2 to V3. This might be causing the problem.

I'll fix it within 1-2 weeks. Please be patient.

**Comment by rfischmann** [comment] 2022-10-21 09:58
Of course, thanks a lot @foooomio!

**Comment by foooomio** [comment] 2022-10-25 14:09
@rfischmann 
Hi, the extension works in my environment with Firefox 106. Can you tell me the situation?

Anyway, I'll make it support MV3, so maybe it will be fixed.

**Comment by foooomio** [comment] 2022-10-25 17:18
I misunderstood. Firefox 106 does not support MV3 yet, but Event Pages finally after many years.

It should work without any modification. Please tell me the situation where it doesn't work well.

**Comment by rfischmann** [comment] 2022-10-25 17:25
Oh wow, before I replied here I decided to remove and reinstall the extension. Now, it's working.

This has never happened before, but… all good now! Sorry for the disturbance.

**Comment by foooomio** [comment] 2022-10-25 18:00
Never mind! Closing.

**Comment by rfischmann** [comment] 2022-11-04 23:43
Yes, I was about to come back here and report the same behavior.

**Comment by woj-tek** [comment] 2022-11-05 10:33
One more soul that was curious why it's not working (it's not visible in context menu) and stumbled against review mentioned by @Speravir and can confirm that after disabling and re-enabling the extension is back in context menu and works without problem.

**Comment by foooomio** [comment] 2022-11-05 11:25
Could you please let me know the steps to reproduce?

**Comment by woj-tek** [comment] 2022-11-05 11:45
I'm not sure if there are any steps. In my case I wanted to get some image and noticed that the menu entry is missing so I started googling. Though, after some testing, it seems quite consistent that after restart the extension item is not visible in context menu but disabling-reenabling brings it back. Looks like some sort of issue with initialisation?

**Comment by foooomio** [comment] 2022-11-06 20:27
Just published v2.10.3 with a bug fix that seems to be the cause. Please try it.

**Comment by woj-tek** [comment] 2022-11-07 07:09
> Just published v2.10.3 with a bug fix that seems to be the cause

In my case it seems to be working fine so far.

**Comment by foooomio** [comment] 2022-11-13 07:04
Thanks, I'll take a look at it. Please let me know again how it will go with the latest version.

**Comment by foooomio** [comment] 2022-11-16 13:30
I have no idea about this bug and don't want to support Firefox anymore. Firefox's MV3 is completely different from Chrome's. I don't want to maintain two versions of the extension.

If you want to use this extension from now on, please describe bugs in detail and tell me what to fix.

**Comment by rfischmann** [comment] 2022-11-17 09:01
Well, there's not much to describe, @foooomio. It's simply not showing up on the contextual menu anymore, so we can't use it at all.

**Comment by rfischmann** [comment] 2022-12-01 17:10
Has anyone found a solution or alternative yet? Thanks.

**Comment by foooomio** [comment] 2022-12-01 18:32
Read my comment above.

**Comment by chr1sx** [comment] 2022-12-02 19:19
It's kind of weird that context menu dissapers after update. Looks like doing following fixes the issue.
**Remove the addon → Add it back from addons.mozilla.org → Restart Firefox**

**Comment by rfischmann** [comment] 2022-12-02 22:41
> It's kind of weird that context menu dissapers after update. Looks like doing following fixes the issue. **Remove the addon → Add it back from addons.mozilla.org → Restart Firefox**
> 
> Another thing I just noticed, is that enabling "Run in Private Windows" will also make context menu dissaper, even if you disable afterwards.

Doesn't work for me…

**Comment by selurvedu** [comment] 2022-12-03 04:06
The menu item dissappeared for me on Firefox 103 as well.

**Comment by foooomio** [comment] 2022-12-03 05:57
Just published v2.10.4.

If you want me to fix it quickly, you should pay the price. You guys are just complaining, aren't you? Never expect developers to do everything for free.

And I hate Firefox. It mimics the Chrome extension API with many incompatibilities. The team claims that Chrome extensions work out of the box in Firefox, but that's not true. Firefox's Event Pages are very buggy. I've decided not to use it for the extension.

To be honest, I don't want support Firefox anymore. I hope Firefox becomes a proper browser.

**Comment by rfischmann** [comment] 2022-12-03 10:26
It seems to be working for me again, @foooomio, thanks!

Nobody said you should fix it quickly, we're helping by reporting bugs and be willing to run any needed tests. You distribute the extension for free and doesn't even have a "donate" button anywhere, why you're now asking us to pay?

I really hope you continue to support the Firefox version, I hate Chrome. But, of course, you're free to do whatever you want with it.

**Comment by foooomio** [comment] 2022-12-03 12:27
@chr1sx said. https://github.com/foooomio/view-background-image/issues/34#issue-1473310127

Bug reports are appreciated. I am grateful for them.

I haven't applied for GitHub Sponsors because it requires a troublesome review. Who will support me when I do that? Instead, I'm considering accepting donations in cryptocurrencies. This is my wallet. Please donate if you feel like it. Thanks.

BTC 1NadiwPMU5T8E6UzHSXj8LyLnia6DCyG7q
ETH 0xf0000cc3a6a66c25dfadb7761d75053b329ccd5c

**Comment by selurvedu** [comment] 2022-12-03 14:11
Thanks for the fix, the addon survives the browser restart now.

> If you want me to fix it quickly, you should pay the price. You guys are just complaining, aren't you? Never expect developers to do everything for free.

We're not in a rush here – at least I am not. I only saw version 104 being mentioned, and decided to add my test result for a previous version. I am sorry you felt pressured because of our comments, you're free to do whatever you want in your own pace, of course. Your licence [clearly states](https://github.com/foooomio/view-background-image/blob/master/LICENSE.txt#L13) that:

> The software is provided "as is", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose [and noninfringement. …]

You have no obligations to us, and we have no right to demand anything. :)

I feel like it's simpler: the addon stopped working out of nowhere for a bunch of people at the same time, so they came here looking for a solution and reported it doesn't work for them. That's why it feels like a crowd ran in here.

**Comment by foooomio** [comment] 2022-12-03 14:32
Thank you. I was a little tired.

Closing since it seems to work well.

**Closed by foooomio** 2022-12-03 14:32 UTC
