### ISSUE TITLE
Stopped detecting images a few months ago

### ISSUE THREAD

**Issue by page200** [foooomio/view-background-image#28] opened 2021-09-14 21:36 UTC
## Page URL

The extension stopped detecting images on most pages a few months ago. For example product pages on aliexpress.com

## Image URL

On a product page, the images on the left.

### OS

Windows 10

### Chrome Version

93.0.4577.63 

### Extension Version

2.10.1

**Comment by foooomio** [comment] 2021-09-14 21:54
Hi, thank you for the report.

Unfortunately, I couldn't reproduce the problem in my environment. The image you are talking about is, for example, [this image](https://ae01.alicdn.com/kf/Hc937acaae2d944b4901a370ae2c98c00W/World-Premiere-Global-Version-POCO-M3-Pro-5G-NFC-Dimensity-700-Smartphone-90Hz-6-5.jpg_Q90.jpg_.webp) on [this page](https://www.aliexpress.com/item/1005002516008793.html)?

Please make sure the extension has permission to run on all sites on `chrome://extensions/?id=cegndknljaapfbnmfnagomhhgbajjibd`.

**Comment by page200** [comment] 2021-09-15 06:34
Yes, the page and image you linked are affected.

The extension has permission to run on all sites on `chrome://extensions/?id=cegndknljaapfbnmfnagomhhgbajjibd`

It says "Failed to get the background image."

I solved the problem on this page: I deactivated another extension, namely `eincidpmnaillhplpojcdkihalpimmod`. However, I had activated that other extension in the first place in an attempt to get results on pages where your extension a few months ago stopped working. If I come across such pages again, I'll let you know. But maybe that is fixed already.

Thanks for your great extension, it is extremely useful! :)

**Comment by foooomio** [comment] 2021-09-15 07:13
That's good, but it seems strange to me because I don't think that extension affects the problem and I haven't changed anything about the logic of this extension for a few years.

Anyway, please let me know if you have any problems. Closing this issue.

**Comment by page200** [comment] 2021-09-19 18:33
Found a website where it doesn't work: instagram.com

**Comment by foooomio** [comment] 2021-09-20 05:05
Sorry but it works on the site in my environment.

**Comment by foooomio** [comment] 2021-09-20 05:16
If possible, could you paste error logs on the site or on the extension. The error logs of the extension can be found by following [this instruction](https://developer.chrome.com/docs/extensions/mv3/tut_debugging/). Make sure collecting errors enabled.

**Comment by page200** [comment] 2021-11-30 07:24
The page you linked to says "Click the **Load Unpacked** button and select the broken extension directory."

What file should I select after clicking **Load Unpacked**?

**Comment by page200** [comment] 2021-11-30 07:45
I cleared cookies, cached files, and hosted app data and restarted Chrome. After **Load Upacked**, I selected the subdirectory of the directory `cegndknljaapfbnmfnagomhhgbajjibd`. I reloaded the page with the image. There was still the same error, but the error wasn't listed when clicking on the **Errors** button from the instructions you sent. There, only a warning was listed - something along the lines of the extension having a fingerprint ID that will be replaced by future manifest. I cleared the warning. It started to work.

**Comment by foooomio** [comment] 2021-11-30 17:40
Sorry, that instraction is not appropriate for you.

Please open `chrome://extensions/?id=nngceckbapebfimnlniiiahkandclblb` and enable to collect errors. Then, try to get the image and the Erros button will be shown.

**Comment by page200** [comment] 2021-11-30 20:22
It's actually still not working on any images on instagram. Developer mode is enabled, the extension displays an error when trying to load the image, but no **Errors** button is showing.

![image](https://user-images.githubusercontent.com/69221289/144121868-c90e3f21-12ac-4f2a-be51-fc5925c148fb.png)

![image](https://user-images.githubusercontent.com/69221289/144122106-166d478c-f47b-4e74-9335-865ed26c0b8a.png)

**Comment by foooomio** [comment] 2021-12-01 08:47
You don't have to use the unpacked extension. Use one that you installed on Chrome Web Store and try to collect errors.

**Comment by foooomio** [comment] 2022-10-25 18:03
Closing for lack of information.

**Closed by foooomio** 2022-10-25 18:03 UTC

**Comment by page200** [comment] 2022-10-25 18:31
I enabled **Collect errors**, but the **Errors** button is still missing (like in the screenshot above) after I get the error. What could be the reason?

The extension isn't working for me on instagram.com.

On product pages on aliexpress.com, it works, but not in incognito mode.

I have a similar problem with the extension [Copy Selected Links](https://chrome.google.com/webstore/detail/copy-selected-links/kddpiojgkjnpmgiegglncafdpnigcbij): it doesn't detect most of the links on some pages.

I tried deactivating all other extensions, a few at a time, but that didn't help.

**Comment by foooomio** [comment] 2022-10-25 18:53
It works in my environment. Please try reinstalling. If it still doesn't work, give it up.

**Comment by page200** [comment] 2022-10-25 21:40
Reinstalling doesn't help. Switching to a different computer and synching doesn't help. The problem seems to be caused by something in my synched profile. But not individual extensions - I tried. Maybe a combination of three certain extensions or something like that? I'll try Chrome with `--disable-extensions-except`.

What could be the reason for the missing **Errors** button?

I'm not yet ready to give up because the extension would be a great help, and it works for many people, so there is hope. I don't quite understand how this is even possible.

**Comment by page200** [comment] 2022-10-26 00:10
It works when I do `"C:\Program Files\Google\Chrome\Application\chrome.exe" --disable-extensions-except="%APPDATA%\..\Local\Google\Chrome\User Data\Default\Extensions\cegndknljaapfbnmfnagomhhgbajjibd\2.10.2_0"`

However, it didn't work when I tried disabling each extension, a few extensions at a time (rather than all at a time). So I have _several_ (sets of) extensions _each_ of which prevents your extension from working. Now I have to save the list of enabled extensions, disable (or uninstall) all, and start a smart search. 🤦

I'm not sure whether disabling them would be enough, or uninstalling them might be necessary. (`--disable-extensions-except` behaves as if they're not installed.)

**Comment by foooomio** [comment] 2022-10-30 06:50
I can't reproduce the bug. Please let me know if you find the cause of the problem. Then I'll fix it.

**Comment by page200** [comment] 2022-11-02 21:15
I'll disable all extensions and try to remember checking whenever I enable any extension.
